// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModels
{
	[Table("ates_tasks")]
	public class AtesTask
	{
		[Column("id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
		public int Id { get; set; } // integer
		
		[Column("name")] 
		public string? Name { get; set; } // character varying
		
		[Column("description")] 
		public string? Description { get; set; } // character varying

		[Column("status_id")] public int StatusId { get; set; } // integer
		
		[Column("assigned_user")]
		public Guid AssignedUser { get; set; } // uuid
		
		[Column("public_id")] 
		public Guid PublicId { get; set; } = Guid.NewGuid(); // uuid

		#region Associations
		/// <summary>
		/// ates_task_status_id_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(StatusId), OtherKey = nameof(TaskStatus.Id))]
		public TaskStatus Status { get; set; } = null!;
		#endregion
	}
}
