// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModels
{
	[Table("task_statuses")]
	public class TaskStatus
	{
		[Column("id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
		public int Id { get; set; } // integer
		
		[Column("status_name")] 
		public string? StatusName { get; set; } // character varying

		#region Associations
		/// <summary>
		/// ates_task_status_id_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(AtesTask.StatusId))]
		public IEnumerable<AtesTask> AtesTasks { get; set; } = null!;
		#endregion
	}
}
