// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModels
{
	[Table("users")]
	public class User
	{
		[Column("id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] 
		public int Id { get; set; } // integer
		
		[Column("username")] public string? Username  { get; set; } // character varying
		
		[Column("role_id")] public int RoleId { get; set; } // integer
		
		[Column("is_deleted")] public bool? IsDeleted { get; set; } = false; // boolean
		
		[Column("public_id")] public Guid PublicId { get; set; } = Guid.NewGuid(); // uuid

		#region Associations
		/// <summary>
		/// user_role_id_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(RoleId), OtherKey = nameof(UserRole.Id))]
		public UserRole Role { get; set; } = null!;
		#endregion
	}
}
