// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModels
{
	[Table("user_roles")]
	public class UserRole
	{
		[Column("id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] 
		public int Id { get; set; } // integer
		
		[Column("role_name")] 
		public string? RoleName { get; set; } // character varying

		#region Associations
		/// <summary>
		/// user_role_id_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(User.RoleId))]
		public IEnumerable<User> Users { get; set; } = null!;
		#endregion
	}
}
